<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('create_update_editora') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?><!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?><b> Editora</b></h2>
            <a href="<?= DOMINIO ?>editora/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados da editora</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "editora/cadastro" : DOMINIO . "editora/alterar" ?>" enctype="multipart/form-data" method="POST" id="cadastroEditora">
              <div class="personal-image">
                <label class="label">
                  <input type="file" class="imagem" id="imagemEditora" name="imagemEditora" onchange="previewImagem()" />
                  <figure class="mt-3 personal-figure">
                    <img id="upload-img" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar" alt="avatar">
                    <figcaption class="personal-figcaption">
                      <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idEditora'] : ""; ?>" class="form-control" id="idEditora" name="idEditora">
              </div>
              <div class="form-group">
                <label for="descricaoEditora">Tipo de Editora</label>
                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoEditora'] : ""; ?>" class="form-control" id="descricaoEditora" name="descricaoEditora" placeholder="Coloque uma descrição...">
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                <a href="<?= DOMINIO ?>editora/listagem" class="btn ml-1 bg-light">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";?>


  <script>
    $(function() {
      $("#cadastroEditora").on('submit', function() {
        var erros = "";
        var file = document.getElementById("imagemEditora");
        erros += $("#descricaoEditora").val().length <= 0 ? "Nome da editora inválido!<br/>" : "";
        erros += file.files.length === 0 ? "Imagem inválida!" : "";
        if (erros.length > 0) {
          $("#modal_retorno .modal-title").html("Erros encontrados!");
          $("#modal_retorno").addClass('modal-danger');
          $("#modal_retorno .modal-body p").html(erros).css({
            'color': 'black'
          });
          $("#modal_retorno").modal('show');


          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>
<?php require_once ARQUIVOS . 'modais/modal_retorno.php'; ?>
</html>