<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('create_update_emprestimo') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?><!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><b>Empréstimo de Livros</b></h2>
            <a href="<?= DOMINIO ?>tipoleitor/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do empréstimo</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "emprestimo/cadastro" : DOMINIO . "emprestimo/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroTipoLeitor">


                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Dados do Empréstimo</button>
                    </li>
                    <li>&nbsp;</li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Livros</button>
                    </li>
                    <li>&nbsp;</li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Carrinho <span class="badge badge-pill badge-danger" id="books">0</span></button>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                        <div class="form-row">

                            <div class="form-group col-md-4">
                                <label for="descricaoTipo">Id empréstimo</label>
                                <input type="text" readonly value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoTipo'] : ""; ?>" class="form-control" id="descricaoTipo" name="descricaoTipo" placeholder="AUTOMÁTICO">
                            </div>

                            <div class="form-group col-md-4">
                                <label for="descricaoTipo">Data empréstimo</label>
                                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoTipo'] : ""; ?>" class="form-control" id="descricaoTipo" name="descricaoTipo" placeholder="00/00/0000">
                            </div>

                            <div class="form-group col-md-4">
                                <label for="descricaoTipo">Data devolução</label>
                                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoTipo'] : ""; ?>" class="form-control" id="descricaoTipo" name="descricaoTipo" placeholder="00/00/0000">
                            </div>

                            <div class="form-group col-md-12">
                                <label for="inputEstado">Leitor</label>
                                <select id="inputEstado" class="form-control">
                                    <option selected>Selecione um leitor...</option>
                                    <?php

                                    if(isset($view_leitores) && count($view_leitores) > 0){
                                        foreach($view_leitores as $leitor){
                                            echo "<option value='$leitor[idLeitor]'>$leitor[nomeLeitor]</option>";
                                        }
                                    }

                                    ?>
                                </select>
                            </div>




                        </div>
                    </div>
                    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">

                        <table class="table table-bordered v-middle" id="listagemLivro">
                            <thead class="thead-dark">
                            <tr class="text-center align-middle">
                                <th style="width: 6%;">ID</th>
                                <th style="width: 15%;">Imagem</th>
                                <th style="width: 12%;">Título</th>
                                <th style="width: 15%;">Observações</th>
                                <th style="width: 10%;">Lançamento</th>
                                <th style="width: 12%;">Editora</th>
                                <th style="width: 8%;">Ação</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            if (isset($view_listagem) && count($view_listagem) > 0) {
                                foreach ($view_listagem as $livro) {
                                    ?>
                                    <tr class="text-center v-middle">
                                        <td><?= $livro['idLivro'] ?></td>
                                        <td>
                                            <?php
                                            $imagem = "http://" . SITE_ROOT . "web-pages/assets/images/livro/" . $livro['imagemCapa'];
                                            if (!Helpers::URL_exists($imagem)) {
                                                $imagem = "http://" . SITE_ROOT . "web-pages/assets/images/avatar.png";
                                            }
                                            ?>
                                            <img class="imagemList" src="<?= $imagem ?>">
                                        </td>
                                        <td><?= $livro['tituloLivro'] ?></td>
                                        <td><?= $livro['observacoesLivro'] ?></td>
                                        <td><?= date('d/m/Y', strtotime($livro['dataLancamento'])) ?></td>
                                        <td><?= $livro['descricaoEditora'] ?></td>
                                        <td>
                                            <a class="btn btn-link selecionar" href="#" data-id="<?= $livro['idLivro'] ?>" data-titulo="<?= $livro['tituloLivro'] ?>" data-toggle="tooltip"><i class="fa fa-plus"></i></a>
                                        </td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                            </tbody>
                        </table>

                    </div>
                    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">

                        <form action="<?=DOMINIO?>emprestimo/index/">
                            <table class="table table-bordered v-middle" id="livrosSelecionados">
                                <thead class="thead">
                                <tr class="text-center align-middle">
                                    <th style="width: 6%;">ID</th>
                                    <th style="width: 15%;">Imagem</th>
                                    <th style="width: 12%;">Título</th>
                                    <th style="width: 15%;">Observações</th>
                                    <th style="width: 10%;">Lançamento</th>
                                    <th style="width: 12%;">Editora</th>
                                    <th style="width: 8%;">Ação</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>

                            <div class="btn-cadastrar">
                                <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                                <a href="<?= DOMINIO ?>emprestimo/listagem" class=" btn ml-1 bg-light">Cancelar</a>
                            </div>
                        </form>

                    </div>
                </div>




              <?php
              require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";
              ?>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    $(function() {


        $('#listagemLivro').DataTable({

            "iDisplayLength": 100,

            "language": {
                "lengthMenu": "",
                "zeroRecords": "Nada encontrado",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Nenhum registro disponível",
                "infoFiltered": "(filtrado de _MAX_ registros no total)",
                "sSearch": "Buscar: ",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Seguinte",
                    "sPrevious": "Anterior"
                },
            }
        });


        $("#pills-profile").on('click','table#listagemLivro tbody tr td a.selecionar',function(e){
            e.preventDefault();

            //alert('clicou');
            // var linha = $(this).attr('data-linha');



            var newRow = $("<tr>");
            var cols = "";

            cols += '<td><input type="hidden" name="arr_id_livro[]" value="'+$(this).parent().siblings("td:eq(0)").text()+'">'+$(this).parent().siblings("td:eq(0)").text()+'</td>';
            cols += '<td><center>'+$(this).parent().siblings("td:eq(1)").html()+'</center></td>';
            cols += '<td>'+$(this).parent().siblings("td:eq(2)").text()+'</td>';
            cols += '<td>'+$(this).parent().siblings("td:eq(3)").text()+'</td>';
            cols += '<td>'+$(this).parent().siblings("td:eq(4)").text()+'</td>';
            cols += '<td>'+$(this).parent().siblings("td:eq(5)").text()+'</td>';
            cols += '<td>';
            cols += '<a href="" class="btn btn-link remover"><i class="fa fa-remove"></i></a>';
            cols += '</td>';

            newRow.append(cols);
            $("#livrosSelecionados").append(newRow);

            var rowCount = $("#livrosSelecionados tbody tr").length;
            $("#books").html(rowCount);

        });

        $("#pills-contact").on('click','table#livrosSelecionados tbody tr td a.remover',function(e){
            e.preventDefault();

            $(this).closest("tr").remove();

            var rowCount = $("#livrosSelecionados tbody tr").length;
            $("#books").html(rowCount);


        });
    });
  </script>
</body>

</html>