<?php
Validar::validarLogin();
if (ValidarPagina::validarPaginaAtual('create_update_livro') <= 0) {
  header("Location: " . DOMINIO . "home");
}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?>
<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <link rel="stylesheet" href="http://<?= SITE_ROOT ?>/web-pages/js/bootstrap-multiselect.css">

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?><b> Livro</b></h2>
            <a href="<?= DOMINIO ?>livro/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do livro</h4>
            <div class="mt-4" style="background-color: white;">
              <div class="row">
                <div class="col col-md-6" style="border-right: 2px solid #EEEEEE;">
                  <form action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "livro/cadastro" : DOMINIO . "livro/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroLivro">
                    <div class="row">
                      <div class="col-11">
                        <div class="form-group">
                          <label for="idLivro">Código Livro:</label>
                          <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idLivro'] : ""; ?>" class="form-control" id="idLivro" name="idLivro" placeholder="Clique para gerar um código...">
                        </div>
                      </div>
                      <div class="col-1">
                        <br>
                        <a id="botao" class="mt-2 btn btn-success"><i class="fas fa-key text-white"></i></a>
                      </div>
                    </div>
                    <div class="form-group">
                      <label for="tituloLivro">Título:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['tituloLivro'] : ""; ?>" class="form-control" id="tituloLivro" name="tituloLivro" placeholder="Coloque um título...">
                    </div>
                    <label for="idAutor">Autor(es):</label>
                    <select id="idAutor" class="js-example-basic-single" name="idAutor[]" multiple>
                      <?php
                      if (isset($view_autor) && count($view_autor) > 0) {
                        foreach ($view_autor as $autor) {
                          $selected = $view_update[0]['idAutor'] == $autor['idAutor'] ? "selected" : "";
                          echo '<option value="' . $autor["idAutor"] . '" ' . $selected . '>' . $autor["descricaoAutor"] . '</option>';
                        }
                      } else {
                        echo '<option value = "">Nenhuma editora cadastrada</option>';
                      }
                      ?>
                    </select>
                    <div class="mt-3 form-group">
                      <label for="observacoesLivro">Observações:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['observacoesLivro'] : ""; ?>" class="form-control" id="observacoesLivro" name="observacoesLivro" placeholder="Coloque uma descrição...">
                    </div>
                    <div class="form-group">
                      <label for="sinopseLivro">Sinopse:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['sinopseLivro'] : ""; ?>" class="form-control" id="sinopseLivro" name="sinopseLivro" placeholder="Coloque uma descrição...">
                    </div>
                    <div class="form-group">
                      <label for="dataLancamento">Data de Lançamento:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? date('d/m/Y', strtotime($view_update[0]['dataLancamento'])) : ""; ?>" class="form-control" id="dataLancamento" name="dataLancamento" onkeyup="mascara_data(this, this.value)" maxlength="10" placeholder="Coloque uma data...">
                    </div>
                    <div class="form-group">
                      <label for="totalPaginas">Total de Páginas:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['totalPaginas'] : ""; ?>" class="form-control" id="totalPaginas" name="totalPaginas" placeholder="Coloque uma quantidade...">
                    </div>
                    <div>
                      <label for="tipoLivro">Tipo de Livro:</label>
                      <select class=" form-select" id="tipoLivro" name="tipoLivro">
                        <option value="digital" <?= $view_update[0]['tipoLivro'] == 'digital' ? 'selected' : ''; ?>>Livro Digital</option>
                        <option value="fisico" <?= $view_update[0]['tipoLivro'] == 'fisico' ? 'selected' : ''; ?>>Livro Físico</option>
                      </select>
                    </div>
                    <label for="idEditora">Editora:</label>
                    <select class=" form-select" id="idEditora" name="idEditora" aria-label="Default select example">
                      <?php
                      if (isset($view_editora) && count($view_editora) > 0) {
                        foreach ($view_editora as $editora) {
                          $selected = $view_update[0]['idEditora'] == $editora['idEditora'] ? "selected" : "";
                          echo '<option value="' . $editora["idEditora"] . '" ' . $selected . '>' . $editora["descricaoEditora"] . '</option>';
                        }
                      } else {
                        echo '<option value = "">Nenhuma editora cadastrada</option>';
                      }
                      ?>
                    </select>
                    <div class="form-group">
                      <label for="pdfLivro">Selecione o PDF do Livro:</label>
                      <input type="file" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['pdfLivro'] : ""; ?>" class="inputstl" id="pdfLivro" name="pdfLivro" accept=".pdf">
                    </div>
                    <input type="hidden" name="verificaPdf" id="verificaPdf" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['pdfLivro'] : ""; ?>">
                    <div class="btn-cadastrar">
                      <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                      <a href="<?= DOMINIO ?>livro/listagem" class=" btn ml-1 bg-light">Cancelar</a>
                    </div>
                </div>
                <div class="col col-md-6">
                  <div class="row">
                    <div class="col col-md-12">
                      <h4 class="mt-5 text-center">Selecione a imagem da capa:</h4>
                      <div class="mt-1 personal-image2">
                        <label class="label">
                          <input type="file" class="imagemCapa" id="imagemCapa" name="imagemCapa" />
                          <figure class="personal-figure2">
                            <img id="upload-img-capa" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                            <figcaption class="personal-figcaption2">
                              <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                            </figcaption>
                          </figure>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="mt-5 row">
                    <div class="col col-md-12">
                      <h4 class="mt-5 text-center">Selecione a imagem da thumb:</h4>
                      <div class="mt-1 personal-image2">
                        <label class="label">
                          <input type="file" class="imagemThumb" id="imagemThumb" name="imagemThumb" />
                          <figure class="personal-figure2">
                            <img id="upload-img-thumb" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                            <figcaption class="personal-figcaption2">
                              <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                            </figcaption>
                          </figure>
                        </label>
                      </div>
                    </div>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php"; ?>

  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script type="text/javascript">
    function mascara_data(campo, valor) {
      var mydata = '';
      mydata = mydata + valor;
      if (mydata.length == 2) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
      if (mydata.length == 5) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
    }

    $(document).ready(function() {
      let botao = document.querySelector('#botao');
      let idLivro = document.querySelector('#idLivro');
      botao.addEventListener('click', function() {
        var dateNow = Date.now();
        idLivro.value = dateNow;
      });
    });

    $(document).ready(function() {
      $('.js-example-basic-single').select2({
        width: '100%',
        placeholder: 'Selecione um autor',
        allowClear: true
      });
    });

    $("#cadastroLivro").on('submit', function() {
      var erros = "";
      var file = document.getElementById("imagemCapa");
      var file2 = document.getElementById("imagemThumb");
      var filepdf = document.getElementById("pdfLivro");
      erros += $("#dataLancamento").val().length != 10 ? "Data de lançamento inválida!<br>" : "";
      erros += $("#tituloLivro").val().length <= 3 ? "Título do livro inválido!<br>\n" : "";
      erros += $("#idLivro").val().length <= 0 ? "Id do livro inválido!<br>\n" : "";
      erros += $("#observacoesLivro").val().length <= 6 ? "Observações do livro inválido!<br>\n" : "";
      if ($("#tipoLivro").val() == 'digital') {
        erros += filepdf.files.length === 0 && $('#verificaPdf').val().length <= 0 ? "Pdf do livro inválido!<br>" : "";
        erros += file.files.length === 0 ? "Imagem da capa inválida!<br>" : "";
        erros += file2.files.length === 0 ? "Imagem da thumb inválida!<br>" : "";
        erros += $("#totalPaginas").val().length <= 0 ? "Páginas do livro inválida!<br>\n" : "";
      }
      if (erros.length > 0) {

        $("#modal_retorno .modal-title").html("Erros encontrados!");
        $("#modal_retorno").addClass('modal-danger');
        $("#modal_retorno .modal-body p").html(erros).css({
          'color': 'black'
        });
        $("#modal_retorno").modal('show');


        return false;
      } else {
        return true;
      }
      return false;
    });
  </script>
</body>
<?php require_once ARQUIVOS . 'modais/modal_retorno.php'; ?>

</html>