<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>

    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?> <b>Leitor</b></h2>
            <a href="<?= DOMINIO ?>leitor/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do leitor</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "leitor/cadastro" : DOMINIO . "leitor/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroLeitor">
              <div class="personal-image">
                <label class="label">
                  <input type="file" class="imagem" id="avatarLeitor" name="avatarLeitor" onchange="previewImagem()" />
                  <figure class="mt-3 personal-figure">
                    <img id="upload-img" src="https://img.icons8.com/officel/344/administrator-male.png" class="personal-avatar" alt="avatar">
                    <figcaption class="personal-figcaption">
                      <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idLeitor'] : ""; ?>" class="form-control" id="idLeitor" name="idLeitor">
              </div>
              <div class="form-row">
                <div class="col-8">
                  <label for="nomeLeitor">Nome:</label>
                  <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['nomeLeitor'] : ""; ?>" class="form-control" id="nomeLeitor" name="nomeLeitor" placeholder="Insira um nome...">
                </div>
                <div class="col-4"">
                <label for="idTipo"> <br></label>
                <select class=" form-select" id="idTipo" name="idTipo" aria-label="Default select example">
                  <?php
                  if(isset($view_tipoLeitor) && count ($view_tipoLeitor) > 0){
                    foreach($view_tipoLeitor as $tipoLeitor){
                      echo '<option value="'.$tipoLeitor["idTipo"].'">'.$tipoLeitor["descricaoTipo"].'</option>';
                    }
                  }else{
                    echo '<option value = "">Nenhum tipo de leitor cadastrado</option>';
                  }
                  ?>
                  </select>
                </div>
              </div>
              <div class="mt-2 form-row">
                <div class="col-8">
                  <label for="emailLeitor">E-mail:</label>
                  <input type="email" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['emailLeitor'] : ""; ?>" class="form-control" id="emailLeitor" name="emailLeitor" placeholder="Insira um e-mail...">
                </div>
                <div class="col-4"">
                <label for="sexoLeitor"> <br></label>
                <select class=" form-select" id="sexoLeitor" name="sexoLeitor" aria-label="Default select example">
                  <option value="masculino" <?= isset($view_update) && count($view_update) == 1 && $view_update[0] ["sexoLeitor"] == "masculino" ?  "selected" : ""; ?>>Masculino</option>
                  <option value="feminino" <?= isset($view_update) && count($view_update) == 1 && $view_update[0] ["sexoLeitor"] == "feminino" ?  "selected" : ""; ?>>Feminino</option>
                  </select>
                </div>
              </div>
              <div class="mt-2 form-row">
                <div class="col-8">
                  <label for="loginLeitor">Login:</label>
                  <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['loginLeitor'] : ""; ?>" class="form-control" id="loginLeitor" name="loginLeitor" placeholder="Insira um login...">
                </div>
                <div class="col-4">
                  <label for="senhaLeitor">Senha:</label>
                  <input type="password" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['senhaLeitor'] : ""; ?>" class="form-control" id="senhaLeitor" name="senhaLeitor" placeholder="Insira uma senha...">
                </div>
              </div>
              <div class="mt-3 form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" checked name="statusLeitor" value="ativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0] ["statusLeitor"] == "ativo" ?  "checked" : ""; ?>>Ativo
                </label>
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" name="statusLeitor" value="inativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0] ["statusLeitor"] == "inativo" ?  "checked" : ""; ?>>Inativo
                </label>
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?=$view_tipo_operacao=='inserir'? "Cadastrar":"Alterar"?></button>
                <a href="<?= DOMINIO ?>leitor/listagem" class="btn ml-1 bg-light">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";?>

  <script>
  $(function() {
      $("#cadastroLeitor").on('submit', function() {
        var erros = "";
        var file = document.getElementById("avatarLeitor");
        erros += $("#nomeLeitor").val().length <= 0 ? "Nome do leitor inválido!\n" : "";
        erros += file.files.length === 0 ? "Imagem inválida!" : "";
        if (erros.length > 0) {
          alert(erros);
          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>

</html>