<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('create_update_paginas_painel') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?>
<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?><b> Página do Painel</b></h2>
            <a href="<?= DOMINIO ?>paginaspainel/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados da página do painel</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "paginaspainel/cadastro" : DOMINIO . "paginaspainel/alterar" ?>" method="POST" id="form-paginas-painel">

              <div class="form-group">
                <label for="descricaoAutor">Descrição Página:</label>
                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoPagina'] : ""; ?>" class="form-control" id="descricaoPagina" name="descricaoPagina" placeholder="Coloque o nome da página">
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                <a href="<?= DOMINIO ?>paginaspainel/listagem" class=" btn ml-1 bg-light">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";?>

  <script>
    $(function() {
      $("#form-paginas-painel").on('submit', function() {
        var erros = "";
        erros += $("#descricaoPagina").val().length <= 0 ? "Nome da página inválido!\n" : "";
        if (erros.length > 0) {
          alert(erros);
          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>

</html>