<?php
Validar::validarLogin();
if (ValidarPagina::validarPaginaAtual('create_update_tipo_leitor') <= 0) {
  header("Location: " . DOMINIO . "home");
}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?>
<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?> <b>Usuário</b></h2>
            <a href="<?= DOMINIO ?>usuario/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do usuário</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "usuario/cadastro" : DOMINIO . "usuario/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroUsuario">
              <div class="row">
                <div class="col-6">
                  <div class="form-group">
                    <label for="nomeUsuario">Nome:</label>
                    <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['nomeUsuario'] : ""; ?>" class="form-control" id="nomeUsuario" name="nomeUsuario" placeholder="Insira um nome...">
                  </div>
                </div>
                <div class="col-6">
                  <div class="form-group">
                    <label for=" perfil_usuario">Perfil:</label>
                    <select class=" form-select" id="perfil_usuario" name="perfil_usuario" aria-label="Default select example">
                      <option value="admin" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["perfil_usuario"] == "admin" ?  "selected" : ""; ?>>Admin</option>
                      <option value="aluno" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["perfil_usuario"] == "aluno" ?  "selected" : ""; ?>>Aluno</option>
                      <option value="professor" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["perfil_usuario"] == "professor" ?  "selected" : ""; ?>>Professor</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idUsuario'] : ""; ?>" class="form-control" id="idUsuario" name="idUsuario">
              </div>
              <div class="row">
                <div class="col-6">
                  <div class="form-group">
                    <label for="loginUsuario">Login:</label>
                    <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['loginUsuario'] : ""; ?>" class="form-control" id="loginUsuario" name="loginUsuario" placeholder="Insira um login...">
                  </div>
                </div>
                <div class="col-6">
                  <div class="form-group">
                    <label for="senhaUsuario">Senha:</label>
                    <input type="password" class="form-control" id="senhaUsuario" name="senhaUsuario" placeholder="Insira uma senha...">
                  </div>
                </div>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" checked name="statusUsuario" value="ativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["statusUsuario"] == "ativo" ?  "checked" : ""; ?>>Ativo
                </label>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" name="statusUsuario" value="inativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["statusUsuario"] == "inativo" ?  "checked" : ""; ?>>Inativo
                </label>
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                <a href="<?= DOMINIO ?>usuario/listagem" class=" btn ml-1 bg-light">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php"; ?>

  <script>
    $(function() {
      $("#cadastroUsuario").on('submit', function() {
        var erros = "";
        erros += $("#nomeUsuario").val().length <= 0 ? "Nome de usuário inválido!<br>" : "";
        erros += $("#loginUsuario").val().length <= 3 ? "Login de usuário inválido!<br>" : "";
        erros += $("#senhaUsuario").val().length <= 7 ? "Senha de usuário inválida, a senha deve conter no mínimo 8 caracteres!\n" : "";
        if (erros.length > 0) {
          $("#modal_retorno .modal-title").html("Erros encontrados!");
          $("#modal_retorno").addClass('modal-danger');
          $("#modal_retorno .modal-body p").html(erros).css({
            'color': 'black'
          });
          $("#modal_retorno").modal('show');


          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>
<?php require_once ARQUIVOS . 'modais/modal_retorno.php'; ?>

</html>