<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?> <b>Tipo de Leitor</b></h2>
            <a href="<?= DOMINIO ?>tipoleitor/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do leitor</h4>
            <form class="mt-4" action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "tipoleitor/cadastro" : DOMINIO . "tipoleitor/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroTipoLeitor">
              <div class="form-group">
                <label for="descricaoTipo">Tipo de Leitor</label>
                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoTipo'] : ""; ?>" class="form-control" id="descricaoTipo" name="descricaoTipo" placeholder="Coloque uma descrição...">
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idTipo'] : ""; ?>" class="form-control" id="idTipo" name="idTipo">
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" checked name="statusTipo" value="ativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["statusLeitor"] == "ativo" ?  "checked" : ""; ?>>Ativo
                </label>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input type="radio" class="form-check-input" name="statusTipo" value="inativo" <?= isset($view_update) && count($view_update) == 1 && $view_update[0]["statusLeitor"] == "inativo" ?  "checked" : ""; ?>>Inativo
                </label>
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?= $view_tipo_operacao == 'inserir' ? "Cadastrar" : "Alterar" ?></button>
                <a href="<?= DOMINIO ?>tipoleitor/listagem" class=" btn ml-1 bg-light">Cancelar</a>
              </div>
              <?php
              require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";
              ?>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    $(function() {
      $("#cadastroTipoLeitor").on('submit', function() {
        var erros = "";
        erros += $("#descricaoTipo").val().length <= 0 ? "Tipo de leitor inválido!\n" : "";
        if (erros.length > 0) {
          alert(erros);
          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>

</html>