<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?= $view_tipo_operacao == 'inserir' ? "Cadastro de" : "Alterar" ?><b> Livro</b></h2>
            <a href="<?= DOMINIO ?>livro/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados do livro</h4>
            <div class="mt-4" style="background-color: white;">
              <div class="row">
                <div class="col col-md-6" style="border-right: 2px solid #EEEEEE;">
                  <form action="<?= $view_tipo_operacao == 'inserir' ? DOMINIO . "livro/cadastro" : DOMINIO . "livro/alterar" ?>" method="POST" enctype="multipart/form-data" id="cadastroLivro">
                    <div class="form-group">
                      <label for="tituloLivro">Título:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['tituloLivro'] : ""; ?>" class="form-control" id="tituloLivro" name="tituloLivro" placeholder="Coloque um título...">
                    </div>
                    <div class="form-group">
                      <label for="observacoesLivro">Observações:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['observacoesLivro'] : ""; ?>" class="form-control" id="observacoesLivro" name="observacoesLivro" placeholder="Coloque uma descrição...">
                    </div>
                    <div class="form-group">
                      <label for="sinopseLivro">Sinopse:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['sinopseLivro'] : ""; ?>" class="form-control" id="sinopseLivro" name="sinopseLivro" placeholder="Coloque uma descrição...">
                    </div>
                    <div class="form-group">
                      <label for="dataLancamento">Data de Lançamento:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['dataLancamento'] : ""; ?>" class="form-control" id="dataLancamento" name="dataLancamento" onkeyup="mascara_data(this, this.value)" maxlength="10" placeholder="Coloque uma data...">
                    </div>
                    <div class="form-group">
                      <label for="totalPaginas">Total de Páginas:</label>
                      <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['totalPaginas'] : ""; ?>" class="form-control" id="totalPaginas" name="totalPaginas" placeholder="Coloque uma quantidade...">
                    </div>
                    <label for="idEditora">Editora:</label>
                <select class=" form-select" id="idEditora" name="idEditora" aria-label="Default select example">
                  <?php
                  if(isset($view_editora) && count ($view_editora) > 0){
                    foreach($view_editora as $editora){
                      echo '<option value="'.$editora["idEditora"].'">'.$editora["descricaoEditora"].'</option>';
                    }
                  }else{
                    echo '<option value = "">Nenhuma editora cadastrada</option>';
                  }
                  ?>
                  </select>
                    <div class="form-group">
                      <label for="pdfLivro">Selecione o PDF do Livro:</label>
                      <input type="file" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['pdfLivro'] : ""; ?>" class="inputstl" id="pdfLivro" name="pdfLivro" accept=".pdf">
                    </div>
                    <div class="form-group">
                      <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idLivro'] : ""; ?>" class="form-control" id="idLivro" name="idLivro">
                    </div>
                    <div class="btn-cadastrar">
                      <button type="submit" class="btn btn-info">Cadastrar</button>
                      <button type="button" class="btn ml-1 bg-light">Cancelar</button>
                    </div>
                </div>
                <div class="col col-md-6">
                  <div class="row">
                    <div class="col col-md-12">
                      <h4 class="mt-3 text-center">Selecione a imagem da capa:</h4>
                      <div class="personal-image2">
                        <label class="label">
                          <input type="file" class="imagemCapa" id="imagemCapa" name="imagemCapa" />
                          <figure class="personal-figure2">
                            <img id="upload-img-capa" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                            <figcaption class="personal-figcaption2">
                              <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                            </figcaption>
                          </figure>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col col-md-12">
                      <h4 class="mt-2 text-center">Selecione a imagem da thumb:</h4>
                      <div class="personal-image2">
                        <label class="label">
                          <input type="file" class="imagemThumb" id="imagemThumb" name="imagemThumb" />
                          <figure class="personal-figure2">
                            <img id="upload-img-thumb" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                            <figcaption class="personal-figcaption2">
                              <img src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                            </figcaption>
                          </figure>
                        </label>
                      </div>
                    </div>
                  </div>
                  </form>
                  <?php
                  require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";
                  ?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    function mascara_data(campo, valor) {
      var mydata = '';
      mydata = mydata + valor;
      if (mydata.length == 2) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
      if (mydata.length == 5) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
    }
    $(function() {
      $("#cadastroLivro").on('submit', function() {
        var erros = "";
        var file = document.getElementById("imagemCapa");
        erros += $("#tituloLivro").val().length <= 0 ? "Título do livro inválido!\n" : "";
        erros += file.files.length === 0 ? "Imagem inválida!" : "";
        if (erros.length > 0) {
          alert(erros);
          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>

</html>