<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('create_update_categoria') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?><!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <div class="preloader">
    <div class="lds-ripple">
      <div class="lds-pos"></div>
      <div class="lds-pos"></div>
    </div>
  </div>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?=$view_tipo_operacao=='inserir'? "Cadastro de": "Alterar"?><b> Categoria</b></h2>
            <a href="<?= DOMINIO ?>categoria/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados da categoria</h4>
            <form class="mt-4" action="<?=$view_tipo_operacao=='inserir'? DOMINIO."categoria/cadastro":DOMINIO."categoria/alterar"?>" method="POST" enctype="multipart/form-data" id="cadastroCategoria">
            <div class="personal-image">
                <label class="label">
                  <input type="file" class="imagem" id="imagemCategoria" name="imagemCategoria" onchange="previewImagem()"/>
                  <figure class="mt-3 personal-figure">
                    <img id="upload-img" src="https://img.icons8.com/officel/344/administrator-male.png" class="personal-avatar" alt="avatar">
                    <figcaption class="personal-figcaption">
                      <img  src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idCategoria'] : ""; ?>" class="form-control" id="idCategoria" name="idCategoria">
              </div>
              <div class="form-group">
                <label for="descricaoCategoria">Tipo de Categoria</label>
                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoCategoria'] : ""; ?>"  class="form-control" id="descricaoCategoria" name="descricaoCategoria" placeholder="Coloque uma descrição...">
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?=$view_tipo_operacao=='inserir'? "Cadastrar":"Alterar"?></button>
                <a href="<?= DOMINIO ?>categoria/listagem" class="btn ml-1 bg-light">Cancelar</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>
  <?php require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";?>

  <script>
  $(function() {
      $("#cadastroCategoria").on('submit', function() {
        var erros = "";
        var file = document.getElementById("imagemCategoria");
        erros += $("#descricaoCategoria").val().length <= 0 ? "Nome da categoria inválido<br>" : "";
        erros += file.files.length === 0 ? "Imagem inválida!" : "";
        if (erros.length > 0) {
          $("#modal_retorno .modal-title").html("Erros encontrados!");
          $("#modal_retorno").addClass('modal-danger');
          $("#modal_retorno .modal-body p").html(erros).css({
            'color': 'black'
          });
          $("#modal_retorno").modal('show');


          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>
<?php require_once ARQUIVOS . 'modais/modal_retorno.php'; ?>

</html>