<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <div class="preloader">
    <div class="lds-ripple">
      <div class="lds-pos"></div>
      <div class="lds-pos"></div>
    </div>
  </div>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2>Cadastro de<b> Livro</b></h2>
            <h4>Insira os dados do livro</h4>
            <div style="background-color: white;">
            <div class="row">
              <div class="col col-md-6" style="border-right: 2px solid #EEEEEE;">
                <form action="<?= DOMINIO ?>livro/cadastro" method="POST">
                  <div class="form-group">
                    <label for="tituloLivro">Título:</label>
                    <input type="text" class="form-control" id="tituloLivro" name="tituloLivro" placeholder="Coloque um título...">
                  </div>
                  <div class="form-group">
                    <label for="observacoesLivro">Observações:</label>
                    <input type="text" class="form-control" id="observacoesLivro" name="observacoesLivro" placeholder="Coloque uma descrição...">
                  </div>
                  <div class="form-group">
                    <label for="sinopseLivro">Sinopse:</label>
                    <input type="text" class="form-control" id="sinopseLivro" name="sinopseLivro" placeholder="Coloque uma descrição...">
                  </div>
                  <div class="form-group">
                    <label for="dataLancamento">Data de Lançamento:</label>
                    <input type="text" class="form-control" id="dataLancamento" name="dataLancamento" onkeyup="mascara_data(this, this.value)" maxlength="10" placeholder="Coloque uma data...">
                  </div>
                  <div class="form-group">
                    <label for="dataCadastro">Data de Cadastro:</label>
                    <input type="text" class="form-control" id="dataCadastro" name="dataCadastro" onkeyup="mascara_data(this, this.value)" maxlength="10" placeholder="Coloque uma data...">
                  </div>
                  <div class="form-group">
                    <label for="totalPaginas">Total de Páginas:</label>
                    <input type="text" class="form-control" id="totalPaginas" name="totalPaginas" placeholder="Coloque uma descrição...">
                  </div>
                  <div class="form-group">
                    <label for="pdfLivro">Selecione o PDF do Livro:</label>
                      <input type="file" class="inputstl" id="pdfLivro" name="pdfLivro" accept=".pdf">
                  </div>
                  <div class="btn-cadastrar">
                    <button type="submit" class="btn btn-info">Cadastrar</button>
                    <button type="button" class="btn ml-1 bg-light">Cancelar</button>
                  </div>
                </form>
              </div>
              <div class="col col-md-6">
                <div class="row">
                  <div class="col col-md-12">
                    <h3 class="mt-2 text-center">Selecione a imagem do livro:</h3>
                  <div class="personal-image2">
                <label class="label">
                  <input type="file" class="imagemLivro" id="imagemLivro" name="imagemLivro" />
                  <figure class="personal-figure2">
                    <img id="upload-img-livro" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                    <figcaption class="personal-figcaption2">
                    <img  src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col col-md-12">
                  <h3 class="mt-2 text-center">Selecione a imagem da capa:</h3>
                  <div class="personal-image2">
                <label class="label">
                  <input type="file" class="imagemCapa" id="imagemCapa" name="imagemCapa" onchange="previewImagem()"/>
                  <figure class="personal-figure2">
                    <img id="upload-img-capa" src="https://img.icons8.com/plasticine/344/image.png" class="personal-avatar2" alt="avatar">
                    <figcaption class="personal-figcaption2">
                    <img  src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- End Wrapper -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- All Jquery -->
  <!-- ============================================================== -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/jquery/dist/jquery.min.js"></script>
  <!-- Bootstrap tether Core JavaScript -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/extra-libs/sparkline/sparkline.js"></script>
  <!--Wave Effects -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/waves.js"></script>
  <!--Menu sidebar -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/sidebarmenu.js"></script>
  <!--Custom JavaScript -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/custom.min.js"></script>
  <!--This page JavaScript -->
  <!-- <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/pages/dashboards/dashboard1.js"></script> -->
  <!-- Charts js Files -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/excanvas.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.pie.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.time.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.stack.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.crosshair.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/pages/chart/chart-page-init.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/js/all-script.js"></script>

  <script>
    function mascara_data(campo, valor) {
      var mydata = '';
      mydata = mydata + valor;
      if (mydata.length == 2) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
      if (mydata.length == 5) {
        mydata = mydata + '/';
        campo.value = mydata;
      }
    }
  </script>
</body>

</html>