<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <div class="preloader">
    <div class="lds-ripple">
      <div class="lds-pos"></div>
      <div class="lds-pos"></div>
    </div>
  </div>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <h2><?=$view_tipo_operacao=='inserir'? "Cadastro de": "Alterar"?><b> Categoria</b></h2>
            <a href="<?= DOMINIO ?>categoria/listagem" class="btn btn-info add-new float-right"><i class="fa fa-arrow-left"></i> Voltar</a>
            <h4 class="mt-3">Insira os dados da categoria</h4>
            <form class="mt-4" action="<?=$view_tipo_operacao=='inserir'? DOMINIO."categoria/cadastro":DOMINIO."categoria/alterar"?>" method="POST" enctype="multipart/form-data" id="cadastroCategoria">
            <div class="personal-image">
                <label class="label">
                  <input type="file" class="imagem" id="imagemCategoria" name="imagemCategoria" onchange="previewImagem()"/>
                  <figure class="mt-3 personal-figure">
                    <img id="upload-img" src="https://img.icons8.com/officel/344/administrator-male.png" class="personal-avatar" alt="avatar">
                    <figcaption class="personal-figcaption">
                      <img  src="https://raw.githubusercontent.com/ThiagoLuizNunes/angular-boilerplate/master/src/assets/imgs/camera-white.png">
                    </figcaption>
                  </figure>
                </label>
              </div>
              <div class="form-group">
                <input type="hidden" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['idCategoria'] : ""; ?>" class="form-control" id="idCategoria" name="idCategoria">
              </div>
              <div class="form-group">
                <label for="descricaoCategoria">Tipo de Categoria</label>
                <input type="text" value="<?= isset($view_update) && count($view_update) == 1 ? $view_update[0]['descricaoCategoria'] : ""; ?>"  class="form-control" id="descricaoCategoria" name="descricaoCategoria" placeholder="Coloque uma descrição...">
              </div>
              <div class="btn-cadastrar">
                <button type="submit" class="btn btn-info"><?=$view_tipo_operacao=='inserir'? "Cadastrar":"Alterar"?></button>
                <a href="<?= DOMINIO ?>categoria/listagem" class="btn ml-1 bg-light">Cancelar</a>
              </div>
              <?php
              require_once ARQUIVOS . "_arquivos_gerais/mensagem_header.php";
              ?>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- End Wrapper -->
  <!-- ============================================================== -->
  <!-- ============================================================== -->
  <!-- All Jquery -->
  <!-- ============================================================== -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/jquery/dist/jquery.min.js"></script>
  <!-- Bootstrap tether Core JavaScript -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/extra-libs/sparkline/sparkline.js"></script>
  <!--Wave Effects -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/waves.js"></script>
  <!--Menu sidebar -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/sidebarmenu.js"></script>
  <!--Custom JavaScript -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/custom.min.js"></script>
  <!--This page JavaScript -->
  <!-- <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/pages/dashboards/dashboard1.js"></script> -->
  <!-- Charts js Files -->
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/excanvas.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.pie.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.time.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.stack.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot/jquery.flot.crosshair.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/dist/js/pages/chart/chart-page-init.js"></script>
  <script src="http://<?= SITE_ROOT ?>/web-pages/js/all-script.js"></script>

  <script>
  $(function() {
      $("#cadastroCategoria").on('submit', function() {
        var erros = "";
        var file = document.getElementById("imagemCategoria");
        erros += $("#descricaoCategoria").val().length <= 0 ? "Nome da categoria inválido!\n" : "";
        erros += file.files.length === 0 ? "Imagem inválida!" : "";
        if (erros.length > 0) {
          alert(erros);
          return false;
        } else {
          return true;
        }
        return false;
      });
    });
  </script>
</body>

</html>