<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('listagem_perguntas') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?><!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row"">
            <div class=" container-lg">
          <div class="table-responsive">
            <div class="table-wrapper">
              <div class="table-title">
                <div class="row">
                  <div class="col-sm-8">
                    <h2>Listagem <b>de Perguntas</b></h2>
                  </div>
                  <div class="col-sm-4">
                    <a href="<?= DOMINIO ?>perguntas" class="mt-2 btn btn-success add-new"><i class="fa fa-plus"></i> Novo</a>
                  </div>
                </div>
              </div>
              <table class="table v-middle table-bordered table-light responsive-table" id="listagemTipoLeitor">
                <thead class="thead-dark">
                  <tr class="text-center align-middle">
                    <th style="width: 10%;">ID</th>
                    <th style="width: 20%;">Pergunta</th>

                    <th style="width: 10%;"></th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  if (isset($view_listagem) && count($view_listagem) > 0) {
                    foreach ($view_listagem as $perguntas) {
                  ?>
                      <tr class="text-center v-middle">
                        <td><?= $perguntas['id'] ?></td>
                        <td><?= $perguntas['pergunta'] ?></td>
                        <td>
                          <a class="edit editar" href="<?= DOMINIO ?>tipoleitor/index/action/update/id/<?= $perguntas['idTipo'] ?>" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                          <a class="delete remover" desc="<?= $perguntas['descricaoTipo'] ?>" id="<?= $perguntas['idTipo'] ?>" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>
                      </tr>
                  <?php
                    }
                  }
                  ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    $(document).ready(function() {
      var dat = new Date();
      var data_dia = dat.getDate() + "/" + (dat.getMonth() + 1) + "/" + dat.getFullYear();
      $('#listagemTipoLeitor').DataTable({
        'dom': '<"top"<"left-col"B><"center-col"l><"right-col"f>>rtip',
        "iDisplayLength": 20,
        "ordering": false,
        "initComplete": function() {
          $("#listagemTipoLeitor").show();
        },
        buttons: [
          'searchBuilder',
          {
            extend: 'excelHtml5',
            text: '<button class="btn btn-sm btn-link"><i  style="color: green" class="fa fa-file-excel-o"></i></button>',
            title: 'Tipo de Leitores - ' + data_dia,
            titleAttr: 'Exportar a Excel',
            exportOptions: {
              columns: [1, 2],
              format: {
                body: function(data, column, row) {
                  if (typeof data === 'string' || data instanceof String) {
                    data = data.replace(/<br\s*\/?>/ig, "\r\n");
                  }
                  return data;
                }
              }
            },
          },
          {
            extend: 'pdfHtml5',
            pageSize: 'A4',
            titleAttr: 'Baixar PDF',
            title: 'Tipo de Leitores - ' + data_dia,
            text: '<button class="btn btn-sm btn-link red"><i style="color: red" class="fa fa-file-pdf-o"></i> ',
            exportOptions: {
              columns: [1, 2],
              format: {
                body: function(data, column, row) {
                  if (typeof data === 'string' || data instanceof String) {
                    data = data.replace(/<br\s*\/?>/ig, "\r\n");
                  }
                  return data;
                }
              }
            },
            customize: function(doc) {

              doc.defaultStyle.alignment = 'left';
              doc.styles.tableHeader.alignment = 'left';

              doc['footer'] = (function(page, pages) {
                return {
                  columns: [
                    'Casa do Bom Menino de Arapongas',
                    {
                      alignment: 'right',
                      text: [{
                          text: page.toString(),
                          italics: true
                        },
                        ' de ',
                        {
                          text: pages.toString(),
                          italics: true
                        }
                      ]
                    }
                  ],
                  margin: [10, 0]
                }
              });


              // Styling the table: create style object
              var objLayout = {};
              // Horizontal line thickness
              objLayout['hLineWidth'] = function(i) {
                return .5;
              };
              // Vertikal line thickness
              objLayout['vLineWidth'] = function(i) {
                return .5;
              };
              // Horizontal line color
              objLayout['hLineColor'] = function(i) {
                return '#aaa';
              };
              // Vertical line color
              objLayout['vLineColor'] = function(i) {
                return '#aaa';
              };
              // Left padding of the cell
              objLayout['paddingLeft'] = function(i) {
                return 4;
              };
              // Right padding of the cell
              objLayout['paddingRight'] = function(i) {
                return 4;
              };
              // Inject the object in the document
              doc.content[1].layout = objLayout;


            }
          },
          {
            extend: 'print',
            pageSize: 'A4',
            title: 'Tipo de Leitores - ' + data_dia,
            text: '<button class="btn btn-sm btn-link"><i style="color: gray" class="fa fa-print"></i></button> ',
            titleAttr: 'Imprimir',
            exportOptions: {
              columns: [1, 2],
              format: {
                body: function(data, column, row) {
                  if (typeof data === 'string' || data instanceof String) {
                    data = data.replace(/<br\s*\/?>/ig, "\r\n");
                  }
                  return data;
                }
              }
            },
          }
        ],
        "language": {
          "lengthMenu": "",
          "zeroRecords": "Nada encontrado",
          "info": "Mostrando página _PAGE_ de _PAGES_",
          "infoEmpty": "Nenhum registro disponível",
          "infoFiltered": "(filtrado de _MAX_ registros no total)",
          "sSearch": "Buscar: ",
          "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Seguinte",
            "sPrevious": "Anterior"
          },
        }
      });
      $(".page-wrapper").on('click', '#listagemTipoLeitor tbody tr td a.remover', function() {
        var id = $(this).attr('id');
        var descricao = $(this).attr('desc');
        var dados = {
          'id': id
        };
        bootbox.confirm({
          message: 'Confirma a exclusão do registro "' + descricao + '" ?',
          callback: function(confirmacao) {

            if (confirmacao) {

              $.ajax({
                url: '<?= DOMINIO ?>tipoleitor/excluir',
                type: 'POST',
                data: dados,
                success: function(retorno) {
                  bootbox.alert(retorno);
                  bootbox.confirm({
                    message: retorno,
                    callback: function(confirma) {
                      if (confirma) {
                        location.reload();
                      }
                    },
                    buttons: {
                      confirm: {
                        label: 'OK',
                        className: 'btn-success'
                      },
                    }
                  })
                }
              });
            }
          },
          buttons: {
            cancel: {
              label: 'Cancelar',
              className: 'btn-default'
            },
            confirm: {
              label: 'EXCLUIR',
              className: 'btn-danger'
            }

          }
        });
      });

    });
  </script>
</body>

</html>