<?php
Validar::validarLogin();
if(ValidarPagina::validarPaginaAtual('listagem_tipo_leitor') <= 0){header ("Location: " . DOMINIO. "home");}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?><!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row"">
            <div class=" container-lg">
          <div class="table-responsive">
            <div class="table-wrapper">
              <div class="table-title">
                <div class="row">
                  <div class="col-sm-8">
                    <h2>Listagem <b>de Usuários</b></h2>
                  </div>
                  <div class="col-sm-4">
                    <a href="<?= DOMINIO ?>usuario" class="mt-2 btn btn-success add-new"><i class="fa fa-plus"></i> Novo</a>
                  </div>
                </div>
              </div>
              <table class="table v-middle" id="listagemUsuario">
                <thead class="thead-dark">
                  <tr class="text-center align-middle">
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Login</th>
                    <th>Status</th>
                    <th>Perfil</th>
                    <th style="width: 10%;"></th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  if (isset($view_listagem) && count($view_listagem) > 0) {
                    foreach ($view_listagem as $usuario) {
                  ?>
                      <tr class="text-center v-middle">
                        <td><?= $usuario['idUsuario'] ?></td>
                        <td><?= $usuario['nomeUsuario'] ?></td>
                        <td><?= $usuario['loginUsuario'] ?></td>
                        <td><?= $usuario['statusUsuario'] ?></td>
                        <td><?= $usuario['perfil_usuario'] ?></td>
                        <td>
                          <a class="edit editar" href="<?= DOMINIO ?>usuario/index/action/update/id/<?= $usuario['idUsuario'] ?>" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                          <a class="delete remover" desc="<?= $usuario['descricaoTipo'] ?>" id="<?= $usuario['idUsuario'] ?>" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                        </td>
                      </tr>
                  <?php
                    }
                  }
                  ?>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    $(document).ready(function() {
      $('#listagemUsuario').DataTable({
        'dom': '<"top"<"left-col"B><"center-col"l><"right-col"f>>rtip',
        "iDisplayLength": 7,
        "initComplete": function() {
          $("#listagemTipoLeitor").show();
        },
        buttons: ['searchBuilder', 'csv', 'excel', 'pdf', 'print'],
        "language": {
          "lengthMenu": "",
          "zeroRecords": "Nada encontrado",
          "info": "Mostrando página _PAGE_ de _PAGES_",
          "infoEmpty": "Nenhum registro disponível",
          "infoFiltered": "(filtrado de _MAX_ registros no total)",
          "sSearch": "Buscar: ",
          "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Seguinte",
            "sPrevious": "Anterior"
          },
        }
      });
      $(".page-wrapper").on('click', '#listagemUsuario tbody tr td a.remover', function() {
        var id = $(this).attr('id');
        var descricao = $(this).attr('desc');
        var dados = {
          'id': id
        };
        bootbox.confirm({
          message: 'Confirma a exclusão do registro "' + descricao + '" ?',
          callback: function(confirmacao) {

            if (confirmacao) {

              $.ajax({
                url: '<?= DOMINIO ?>usuario/excluir',
                type: 'POST',
                data: dados,
                success: function(retorno) {
                  bootbox.alert(retorno);
                  bootbox.confirm({
                    message: retorno,
                    callback: function(confirma) {
                      if (confirma) {
                        location.reload();
                      }
                    },
                    buttons: {
                      confirm: {
                        label: 'OK',
                        className: 'btn-success'
                      },
                    }
                  })
                }
              });
            }
          },
          buttons: {
            cancel: {
              label: 'Cancelar',
              className: 'btn-default'
            },
            confirm: {
              label: 'EXCLUIR',
              className: 'btn-danger'
            }

          }
        });
      });

    });
  </script>
</body>

</html>