<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/preloader.php" ?>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>

    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <div class="table-responsive">
              <div class="table-wrapper">
                <div class="table-title">
                  <div class="row">
                    <div class="col-sm-8">
                      <h2>Listagem de<b> Livro</b></h2>
                    </div>
                    <div class="col-sm-4">
                      <a href="<?= DOMINIO ?>livro" class="mt-2 btn btn-success add-new"><i class="fa fa-plus"></i> Novo</a>
                    </div>
                  </div>
                </div>
                <table class="table table-bordered v-middle" id="listagemLivro">
                  <thead class="thead-dark">
                    <tr class="text-center align-middle">
                      <th style="width: 6%;">ID</th>
                      <th style="width: 15%;">Imagem</th>
                      <th style="width: 12%;">Título</th>
                      <th style="width: 15%;">Sinopse</th>
                      <th style="width: 15%;">Observações</th>
                      <th style="width: 9%;">Data de Lançamento</th>
                      <th style="width: 8%;">Data de Cadastro</th>
                      <th style="width: 12%;">Editora</th>
                      <th style="width: 7%;">Total de Páginas</th>
                      <th style="width: 8%;"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php
                    if (isset($view_listagem) && count($view_listagem) > 0) {
                      foreach ($view_listagem as $livro) {
                    ?>
                        <tr class="text-center v-middle">
                          <td><?= $livro['idLivro'] ?></td>
                          <td>
                            <?php
                            $imagem = "http://" . SITE_ROOT . "web-pages/assets/images/livro/" . $livro['imagemCapa'];
                            if (!Helpers::URL_exists($imagem)) {
                              $imagem = "http://" . SITE_ROOT . "web-pages/assets/images/avatar.png";
                            }
                            ?>
                            <img class="imagemList" src="<?= $imagem ?>">
                          </td>
                          <td><?= $livro['tituloLivro'] ?></td>
                          <td><?= $livro['sinopseLivro'] ?></td>
                          <td><?= $livro['observacoesLivro'] ?></td>
                          <td><?= date('d/m/Y', strtotime($livro['dataLancamento'])) ?></td>
                          <td><?= date('d/m/Y', strtotime($livro['dataCadastro'])) ?></td>
                          <td><?= $livro['descricaoEditora'] ?></td>
                          <td><?= $livro['totalPaginas'] ?></td>
                          <td>
                            <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                            <a class="edit" title="editar" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            <a class="delete" title="deletar" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                          </td>
                        </tr>
                    <?php
                      }
                    }
                    ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- ============================================================== -->
  <!-- SCRIPTS -->
  <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

  <script>
    $(document).ready(function() {
      $('#listagemLivro').DataTable({
        'dom': '<"top"<"left-col"B><"center-col"l><"right-col"f>>rtip',
        "iDisplayLength": 7,
        "initComplete": function() {
          $("#listagemLivro").show();
        },
        buttons: ['searchBuilder', 'csv', 'excel', 'pdf', 'print'],
        "language": {
          "lengthMenu": "",
          "zeroRecords": "Nada encontrado",
          "info": "Mostrando página _PAGE_ de _PAGES_",
          "infoEmpty": "Nenhum registro disponível",
          "infoFiltered": "(filtrado de _MAX_ registros no total)",
          "sSearch": "Buscar: ",
          "oPaginate": {
            "sFirst": "Primero",
            "sLast": "Último",
            "sNext": "Seguinte",
            "sPrevious": "Anterior"
          },
        }
      });
      $(".page-wrapper").on('click', '#listagemLivro tbody tr td a.remover', function() {
        var id = $(this).attr('id');
        var descricao = $(this).attr('desc');
        var dados = {
          'id': id
        };
        bootbox.confirm({
          message: 'Confirma a exclusão do livro "' + descricao + '" ?',
          callback: function(confirmacao) {

            if (confirmacao) {

              $.ajax({
                url: '<?= DOMINIO ?>livro/excluir',
                type: 'POST',
                data: dados,
                success: function(retorno) {
                  bootbox.alert(retorno);
                  bootbox.confirm({
                    message: retorno,
                    callback: function(confirma) {
                      if (confirma) {
                        location.reload();
                      }
                    },
                    buttons: {
                      confirm: {
                        label: 'OK',
                        className: 'btn-success'
                      },
                    }
                  })
                }
              });
            }
          },
          buttons: {
            cancel: {
              label: 'Cancelar',
              className: 'btn-default'
            },
            confirm: {
              label: 'EXCLUIR',
              className: 'btn-danger'
            }

          }
        });
      });

    });
  </script>
</body>

</html>