<?php
Validar::validarLogin();
if (ValidarPagina::validarPaginaAtual('listagem_categoria') <= 0) {
  header("Location: " . DOMINIO . "home");
}
setlocale(LC_TIME, 'pt_BR', 'pt_BR.utf-8', 'pt_BR.utf-8', 'portuguese');
date_default_timezone_set('America/Sao_Paulo');
?>
<!DOCTYPE html>
<html dir="ltr" lang="pt-br">

<?php require_once ARQUIVOS . "_arquivos_gerais/head.php" ?>

<body>
  <!-- ============================================================== -->
  <!-- Preloader - style you can find in spinners.css -->
  <!-- ============================================================== -->
  <div class="preloader">
    <div class="lds-ripple">
      <div class="lds-pos"></div>
      <div class="lds-pos"></div>
    </div>
  </div>

  <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full" data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">

    <?php require_once ARQUIVOS . "_arquivos_gerais/header.php" ?>

    <?php require_once ARQUIVOS . "_arquivos_gerais/navbar.php" ?>
    <div class="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="container-lg">
            <div class="table-responsive">
              <div class="table-wrapper">
                <div class="table-title">
                  <div class="row">
                    <div class="col-sm-8">
                      <h2>Relatório TOP<b> 10 Mensal</b></h2>
                    </div>
                  </div>
                  <form action="<?= DOMINIO ?>relatorio/top10" method="post">
                    <div class="row mt-3" style="margin-left: -28px !important;">
                      <div class="col-sm-3">
                        <div class="form-group">
                          <label>Mês:</label>
                          <select class="form-control select2 required" name="mes" id="mes" style="width: 100%;">
                            <option value="1" <?= date('m') == 1 ? 'selected' : '' ?>>Janeiro</option>
                            <option value="2" <?= date('m') == 2 ? 'selected' : '' ?>>Fevereiro</option>
                            <option value="3" <?= date('m') == 3 ? 'selected' : '' ?>>Março</option>
                            <option value="4" <?= date('m') == 4 ? 'selected' : '' ?>>Abril</option>
                            <option value="5" <?= date('m') == 5 ? 'selected' : '' ?>>Maio</option>
                            <option value="6" <?= date('m') == 6 ? 'selected' : '' ?>>Junho</option>
                            <option value="7" <?= date('m') == 7 ? 'selected' : '' ?>>Julho</option>
                            <option value="8" <?= date('m') == 8 ? 'selected' : '' ?>>Agosto</option>
                            <option value="9" <?= date('m') == 9 ? 'selected' : '' ?>>Setembro</option>
                            <option value="10" <?= date('m') == 10 ? 'selected' : '' ?>>Outubro</option>
                            <option value="11" <?= date('m') == 11 ? 'selected' : '' ?>>Novembro</option>
                            <option value="12" <?= date('m') == 12 ? 'selected' : '' ?>>Dezembro</option>
                          </select>
                        </div>
                      </div>

                      <div class="col-sm-3">
                        <div class="form-group">
                          <label>Ano:</label>
                          <select class="form-control select2 required" name="ano" id="ano" style="width: 100%;">
                            <?php
                            for ($x = 2022; $x <= 2025; $x++) {
                              echo '<option value="' . $x . '">' . $x . '</option>';
                            }
                            ?>
                          </select>
                        </div>
                      </div>

                      <div class="col-sm-3">
                        <div class="form-group">
                          <br>
                          <label></label>
                          <button type="submit" class="mt-2 btn btn-info"><i class="fa fa-search"></i> Buscar</button>
                        </div>
                      </div>
                    </div>
                  </form>
                  <h4 style="font-size: 24px; text-align: center; font-weight: bold;">LISTAGEM <?= $view_mes . "/" . $view_ano ?></h4>
                  <table class="table v-middle table-bordered table-light responsive-table" id="listagemCategoria">
                    <thead class="thead-dark">
                      <tr class="text-center align-middle responsive-table">
                        <th style="width: 5%;">ID Leitor</th>
                        <th style="width: 30%;">Nome Leitor</th>
                        <th style="width: 10%;">Tempo Leitura</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php
                      if (isset($view_listagem) && count($view_listagem) > 0) {
                        foreach ($view_listagem as $top10) {
                      ?>
                          <tr class="text-center v-middle">
                            <td><?= $top10['idLeitor'] ?></td>
                            <td><?= $top10['nomeLeitor'] ?></td>
                            <td><?= Validar::converterSegundosEmHoras($top10['tempoLeituraSegundos']) ?></td>
                          </tr>
                      <?php
                        }
                      }
                      ?>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- ============================================================== -->
    <!-- SCRIPTS -->

    <?php require_once ARQUIVOS . "_arquivos_gerais/scripts.php" ?>

    <script>
      $(document).ready(function() {
        var mes = '<?= $view_mes ?>';
        var dat = new Date();
        var data_dia = mes + "/" + dat.getFullYear();


        $('#listagemCategoria').DataTable({
          'dom': '<"top"<"left-col"B><"center-col"l><"right-col"f>>rtip',
          "iDisplayLength": 10,
          "ordering": false,
          "initComplete": function() {
            $("#listagemCategoria").show();
          },
          buttons: [
            'searchBuilder',
            {
              extend: 'excelHtml5',
              text: '<button class="btn btn-sm btn-link"><i  style="color: green" class="fa fa-file-excel-o"></i></button>',
              title: 'TOP 10 - ' + data_dia,
              titleAttr: 'Exportar a Excel',
              exportOptions: {
                columns: [1, 2],
                format: {
                  body: function(data, column, row) {
                    if (typeof data === 'string' || data instanceof String) {
                      data = data.replace(/<br\s*\/?>/ig, "\r\n");
                    }
                    return data;
                  }
                }
              },
            },
            {
              extend: 'pdfHtml5',
              pageSize: 'A4',
              titleAttr: 'Baixar PDF',
              title: 'TOP 10 - ' + data_dia,
              text: '<button class="btn btn-sm btn-link red"><i style="color: red" class="fa fa-file-pdf-o"></i> ',
              exportOptions: {
                columns: [1, 2],
                format: {
                  body: function(data, column, row) {
                    if (typeof data === 'string' || data instanceof String) {
                      data = data.replace(/<br\s*\/?>/ig, "\r\n");
                    }
                    return data;
                  }
                }
              },
              customize: function(doc) {

                doc.defaultStyle.alignment = 'left';
                doc.styles.tableHeader.alignment = 'left';

                doc['footer'] = (function(page, pages) {
                  return {
                    columns: [
                      'Casa do Bom Menino de Arapongas',
                      {
                        alignment: 'right',
                        text: [{
                            text: page.toString(),
                            italics: true
                          },
                          ' de ',
                          {
                            text: pages.toString(),
                            italics: true
                          }
                        ]
                      }
                    ],
                    margin: [10, 0]
                  }
                });


                // Styling the table: create style object
                var objLayout = {};
                // Horizontal line thickness
                objLayout['hLineWidth'] = function(i) {
                  return .5;
                };
                // Vertikal line thickness
                objLayout['vLineWidth'] = function(i) {
                  return .5;
                };
                // Horizontal line color
                objLayout['hLineColor'] = function(i) {
                  return '#aaa';
                };
                // Vertical line color
                objLayout['vLineColor'] = function(i) {
                  return '#aaa';
                };
                // Left padding of the cell
                objLayout['paddingLeft'] = function(i) {
                  return 4;
                };
                // Right padding of the cell
                objLayout['paddingRight'] = function(i) {
                  return 4;
                };
                // Inject the object in the document
                doc.content[1].layout = objLayout;


              }
            },
            {
              extend: 'print',
              pageSize: 'A4',
              title: 'TOP 10 - ' + data_dia,
              text: '<button class="btn btn-sm btn-link"><i style="color: gray" class="fa fa-print"></i></button> ',
              titleAttr: 'Imprimir',
              exportOptions: {
                columns: [1, 2],
                format: {
                  body: function(data, column, row) {
                    if (typeof data === 'string' || data instanceof String) {
                      data = data.replace(/<br\s*\/?>/ig, "\r\n");
                    }
                    return data;
                  }
                }
              },
            }
          ],
          "language": {
            "lengthMenu": "",
            "zeroRecords": "Nada encontrado",
            "info": "Mostrando página _PAGE_ de _PAGES_",
            "infoEmpty": "Nenhum registro disponível",
            "infoFiltered": "(filtrado de _MAX_ registros no total)",
            "sSearch": "Buscar: ",
            "oPaginate": {
              "sFirst": "Primero",
              "sLast": "Último",
              "sNext": "Seguinte",
              "sPrevious": "Anterior"
            },
          }
        });
      });
    </script>
</body>

</html>